server:
  port: 9527

spring:
  application:
    name: shop-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

#加之前访问路径：http://myzuul.com:9527/shop-provider-dept/dept/get/1
zuul:  #加上后访问路径 :http://myzuul.com:9527/elshop/mydept/dept/get/1
  #ignored-services: microservicecloud-dept
  prefix: /elshop
  ignored-services: "*"
  routes:
    mydept.serviceId: shop-provider-dept
    mydept.path: /mydept/**

info:
  app.name: shop-microcloud
  company.name: www.elitesland.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

