server:
  port: 8002
#  context-path: /shop-provider

#mybatis:
#  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
#  type-aliases-package: com.el.parent.entities    # 所有Entity别名类所在包
#  mapper-locations:
#  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://192.168.137.131:3306/cloudDB01              # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
  redis:
    host: 127.0.0.1
    timeout: 1000
    port: 6379

#mybatis:
#  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
#  type-aliases-package: com.el.parent.entities    # 所有Entity别名类所在包
#  mapper-locations:
#  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
mybatis:
  type-aliases-package: com.el.parent.entities
  #mapper.xml所在位置
  mapper-locations: classpath*:com/el/provider8001/mapper/*.xml
#  mapper-locations: com.el.provider8001.mapper

#zuul:
#  prefix: /shop
#  ignored-patterns: "*"
#  routes:
#    shopdept.serviced: shop-provider-dept
#    shopdept.path: /shopdept/**

